# Generated by Django 5.1.3 on 2024-12-08 16:08

import gelfmp.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelfmp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charcoaliqf',
            options={'verbose_name': 'IQF de Fornecedor de Carvão', 'verbose_name_plural': 'IQFs de Fornecedores de Carvão'},
        ),
        migrations.AlterField(
            model_name='charcoaliqf',
            name='density_percentage',
            field=models.FloatField(validators=[gelfmp.utils.validators.validate_percentage], verbose_name='Densidade Dentro do Limite (%)'),
        ),
        migrations.AlterField(
            model_name='charcoaliqf',
            name='fines_percentage',
            field=models.FloatField(validators=[gelfmp.utils.validators.validate_percentage], verbose_name='Finos Dentro do Limite (%)'),
        ),
        migrations.AlterField(
            model_name='charcoaliqf',
            name='moisture_percentage',
            field=models.FloatField(validators=[gelfmp.utils.validators.validate_percentage], verbose_name='Umidade Dentro do Limite (%)'),
        ),
        migrations.AlterField(
            model_name='charcoaliqf',
            name='month',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês de referência'),
        ),
        migrations.AlterField(
            model_name='charcoaliqf',
            name='programmed_percentage',
            field=models.FloatField(validators=[gelfmp.utils.validators.validate_percentage], verbose_name='Programação Realizada (%)'),
        ),
        migrations.AlterField(
            model_name='charcoaliqf',
            name='year',
            field=models.IntegerField(choices=[(2025, '2025'), (2024, '2024'), (2023, '2023'), (2022, '2022'), (2021, '2021'), (2020, '2020')], verbose_name='Ano de referência'),
        ),
        migrations.AlterField(
            model_name='charcoalmonthlyplan',
            name='month',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês de Referência'),
        ),
        migrations.AlterField(
            model_name='charcoalmonthlyplan',
            name='year',
            field=models.IntegerField(choices=[(2025, '2025'), (2024, '2024'), (2023, '2023'), (2022, '2022'), (2021, '2021'), (2020, '2020')], verbose_name='Ano de Referência'),
        ),
    ]
