# Generated by Django 5.1.3 on 2024-12-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelfmp', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='charcoalentry',
            index=models.Index(fields=['supplier'], name='gelfmp_char_supplie_c9b051_idx'),
        ),
        migrations.AddIndex(
            model_name='charcoalentry',
            index=models.Index(fields=['dcf'], name='gelfmp_char_dcf_08fc47_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['cpf_cnpj'], name='gelfmp_supp_cpf_cnp_4b5790_idx'),
        ),
    ]
