# Generated by Django 5.1.3 on 2024-12-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelfmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='geojson',
            field=models.JSONField(blank=True, null=True, verbose_name='GeoJSON'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('ctf', 'CADASTRO TÉCNICO FEDERAL'), ('lic_ambiental', 'LICENÇA AMBIENTAL'), ('exemption', 'DISPENSA'), ('reg_ief', 'REGISTRO IEF'), ('car', 'CADASTRO AMBIENTAL RURAL'), ('state_registration', 'INSCRIÇÃO ESTADUAL'), ('municipal_registration', 'INSCRIÇÃO MUNICIPAL'), ('cnpj_lookup', 'CONSULTA CNPJ'), ('shapefile', 'SHAPEFILE'), ('other', 'OUTRO')], max_length=50, verbose_name='Tipo de Documento'),
        ),
    ]
