# Generated by Django 5.1.3 on 2024-12-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelfmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charcoalmonthlyplan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Somente aplicável a GELF.', max_digits=6, null=True, verbose_name='Preço (R$)'),
        ),
    ]
