# Generated by Django 5.1.4 on 2024-12-31 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelfmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charcoalcontract',
            name='gelf_signed',
            field=models.BooleanField(default=False, verbose_name='Assinatura da GELF'),
        ),
        migrations.AddField(
            model_name='charcoalcontract',
            name='legal_department_signed',
            field=models.BooleanField(default=False, verbose_name='Assinatura do Jurídico'),
        ),
        migrations.AddField(
            model_name='charcoalcontract',
            name='supplier_signed',
            field=models.BooleanField(default=False, verbose_name='Assinatura do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='charcoalentry',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charcoal_entries', to='gelfmp.supplier', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='charcoaliqf',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='iqfs', to='gelfmp.supplier', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='document',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='gelfmp.supplier', verbose_name='Fornecedor'),
        ),
    ]
