# Generated by Django 5.1.4 on 2024-12-22 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelfmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='account_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Insira um CNPJ válido. Use apenas numeros ou 00.000.000/0000-00.', regex='^(\\w{14}|\\d{2}.\\d{3}.\\d{3}/\\d{4}-\\d{2})$')], verbose_name='CNPJ da Conta'),
        ),
    ]
