# Generated by Django 5.1.3 on 2024-12-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gelfmp', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='charcoalentry',
            new_name='gelfmp_char_entry_d_506da5_idx',
            old_name='gelfmp_ch_entry_d_77632d_idx',
        ),
        migrations.RenameIndex(
            model_name='supplier',
            new_name='gelfmp_supp_materia_72a935_idx',
            old_name='gelfmp_su_materia_fd0e12_idx',
        ),
        migrations.RenameIndex(
            model_name='supplier',
            new_name='gelfmp_supp_state_i_b538ae_idx',
            old_name='gelfmp_su_state_i_7dbac4_idx',
        ),
    ]
