# Generated by Django 5.1.4 on 2025-01-02 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelfmp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='gelfmp.supplier', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='charcoaliqf',
            name='year',
            field=models.IntegerField(choices=[(2026, '2026'), (2025, '2025'), (2024, '2024'), (2023, '2023'), (2022, '2022'), (2021, '2021'), (2020, '2020')], verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='charcoalmonthlyplan',
            name='year',
            field=models.IntegerField(choices=[(2026, '2026'), (2025, '2025'), (2024, '2024'), (2023, '2023'), (2022, '2022'), (2021, '2021'), (2020, '2020')], verbose_name='Ano'),
        ),
    ]
