# Generated by Django 5.1.3 on 2024-12-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelfmp', '0002_charcoalentry_gelfmp_char_supplie_c9b051_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(blank=True, choices=[('gelf', 'GELF'), ('botumirim', 'Botumirim'), ('third_party', 'Terceiro')], max_length=100, null=True, verbose_name='Tipo de Fornecedor'),
        ),
    ]
