# Generated by Django 5.1.4 on 2025-01-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelfmp', '0003_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcf',
            name='available_volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Volume Disponível (m³)'),
        ),
        migrations.AlterField(
            model_name='dcf',
            name='declared_volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Volume Declarado (m³)'),
        ),
    ]
