# Generated by Django 5.1.3 on 2024-12-19 00:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelfmp', '0003_supplier_supplier_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='cep',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Insira um CEP válido. Use o formato 00000000 ou 00000-000.', regex='^(\\d{8}|\\d{5}-\\d{3})$')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(blank=True, choices=[('gelf', 'GELF'), ('botumirim', 'Botumirim'), ('third_party', 'Terceiro')], max_length=100, null=True, verbose_name='Tipo de Fornecedor (Carvão)'),
        ),
    ]
