# Generated by Django 5.1.3 on 2024-12-20 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelfmp', '0004_alter_supplier_cep_alter_supplier_supplier_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='Insira um CPF ou CNPJ válido. Use apenas numeros ou 000.000.000-00, 00.000.000/0000-00.', regex='^(\\w{14}|\\d{11}|\\d{3}.\\d{3}.\\d{3}-\\d{2}|\\d{2}.\\d{3}.\\d{3}/\\d{4}-\\d{2})$')], verbose_name='CPF'),
        ),
    ]
