# Generated by Django 5.1.4 on 2024-12-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelfmp', '0004_alter_task_options_alter_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charcoalcontract',
            name='price',
            field=models.FloatField(default=2, verbose_name='Preço (R$)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Descrição'),
        ),
    ]
