[project]
name = "gsid-mp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django-jazzmin>=3.0.1",
    "django>=5.1.3",
    "pydantic-settings>=2.6.1",
    "taskipy>=1.14.0",
]

[tool.ruff.format]
preview = true
quote-style = 'single'

[tool.taskipy.tasks]
run = "python manage.py runserver"