[project]
name = "gsid-mp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django-cors-headers>=4.6.0",
    "django-tailwind>=3.8.0",
    "django-unfold>=0.40.0",
    "django>=5.1.3",
    "faker>=30.8.2",
    "httpx>=0.27.2",
    "loguru>=0.7.2",
    "pydantic-settings>=2.6.1",
    "taskipy>=1.14.0",
]

[tool.ruff]
line-length = 120

[tool.ruff.format]
preview = true
quote-style = 'single'

[tool.taskipy.tasks]
run = "python src/manage.py runserver"
su = "python src/manage.py createsuperuser"
makemigrations = "python src/manage.py makemigrations"
migrate = "python src/manage.py migrate"
