# Generated by Django 5.1.3 on 2024-11-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='material_type',
            field=models.CharField(max_length=30, verbose_name='Tipo de Material'),
        ),
    ]
