# Generated by Django 5.1.3 on 2024-12-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charcoalentry',
            name='rm_code',
        ),
        migrations.AddField(
            model_name='supplier',
            name='rm_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Código RM'),
        ),
    ]
