# Generated by Django 5.1.3 on 2024-11-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_supplier_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='corporate_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Razão Social'),
        ),
    ]
