# Generated by Django 5.1.3 on 2024-12-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_remove_charcoalentry_rm_code_supplier_rm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charcoalentry',
            name='entry_volume',
            field=models.FloatField(verbose_name='Volume de Entrada (m³)'),
        ),
        migrations.AlterField(
            model_name='charcoalentry',
            name='fines',
            field=models.FloatField(verbose_name='Finos (%)'),
        ),
        migrations.AlterField(
            model_name='charcoalentry',
            name='moisture',
            field=models.FloatField(verbose_name='Umidade (%)'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='material_type',
            field=models.CharField(choices=[('Minério de Ferro', 'Minério de Ferro'), ('Subprodutos', 'Subprodutos'), ('Carvão Vegetal', 'Carvão Vegetal'), ('Bauxita', 'Bauxita'), ('Argila', 'Argila'), ('Areia', 'Areia'), ('Calcario', 'Calcario'), ('FeSiMg', 'FeSiMg'), ('Ferroligas', 'Ferroligas'), ('Mistura', 'Mistura'), ('Fluorita', 'Fluorita'), ('Dolomita', 'Dolomita'), ('Grafite', 'Grafite')], max_length=100, verbose_name='Tipo de Material'),
        ),
    ]
