# Generated by Django 5.1.3 on 2024-12-05 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_charcoalentry_entry_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cep',
            field=models.CharField(help_text='Insira apenas os números.', max_length=8, validators=[django.core.validators.RegexValidator(message='Insira um CEP válido, digitando apenas os números.', regex='^\\d{8}$')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='corporate_name',
            field=models.CharField(help_text='Insira nomes padronizados para evitar inconsistência, como o próprio nome que consta no CNPJ.', max_length=200, unique=True, verbose_name='Razão Social'),
        ),
    ]
