# Generated by Django 5.1.3 on 2024-11-29 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_supplier_corporate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(verbose_name='Data de Entrada')),
                ('origin_ticket', models.CharField(max_length=50, verbose_name='Ticket de Origem')),
                ('vehicle_plate', models.CharField(max_length=50, verbose_name='Placa do Veículo')),
                ('entry_volume', models.FloatField(verbose_name='Volume de Entrada')),
                ('humidity', models.FloatField(verbose_name='Umidade de Origem')),
                ('fines', models.FloatField(verbose_name='Finos')),
                ('density', models.FloatField(verbose_name='Densidade')),
                ('dcf', models.CharField(max_length=50, verbose_name='DCF')),
                ('gcae', models.CharField(max_length=50, verbose_name='GCAE')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charcoal_entries', to='map.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Entrada de Carvão',
                'verbose_name_plural': 'Entradas de Carvão',
            },
        ),
    ]
