# Generated by Django 5.1.3 on 2024-11-29 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_coalentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoalEntry',
            new_name='CharcoalEntry',
        ),
    ]
