# Generated by Django 5.1.3 on 2024-12-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_supplier_active_alter_supplier_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Fornecedor Ativo'),
        ),
    ]
