# Generated by Django 5.1.3 on 2024-11-29 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_rename_coalentry_charcoalentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charcoalentry',
            old_name='humidity',
            new_name='moisture',
        ),
    ]
