# Generated by Django 5.1.3 on 2024-12-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_supplier_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
    ]
