# Generated by Django 5.1.3 on 2024-11-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_rename_humidity_charcoalentry_moisture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charcoalentry',
            name='origin_ticket',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ticket de Origem'),
        ),
        migrations.AddIndex(
            model_name='charcoalentry',
            index=models.Index(fields=['entry_date'], name='map_charcoa_entry_d_db53ed_idx'),
        ),
    ]
