# Generated by Django 5.1.3 on 2024-11-08 23:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('sigla', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.estado')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FornecedorMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, max_length=200)),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$')])),
                ('tipo_material', models.CharField(choices=[('CAR', 'Carvão Vegetal'), ('MIN', 'Minério')], max_length=3)),
                ('certificacao_ambiental', models.BooleanField(default=False)),
                ('licenca_operacao', models.CharField(blank=True, max_length=50)),
                ('registro_ibama', models.CharField(blank=True, max_length=50)),
                ('ultima_avaliacao', models.DateField(blank=True, null=True)),
                ('nota_qualidade', models.DecimalField(decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('coordenadas_gps', models.CharField(blank=True, max_length=100)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_compra', models.DateField(blank=True, null=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores', to='map.cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores', to='map.estado')),
            ],
            options={
                'verbose_name': 'Fornecedor de Matéria Prima',
                'verbose_name_plural': 'Fornecedores de Matéria Prima',
                'ordering': ['razao_social'],
                'indexes': [models.Index(fields=['tipo_material'], name='map_fornece_tipo_ma_1a7c4d_idx'), models.Index(fields=['estado'], name='map_fornece_estado__493658_idx')],
            },
        ),
    ]
