# Generated by Django 5.1.3 on 2024-11-10 14:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('sigla', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.estado')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='InfoRota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('distancia_em_metros', models.IntegerField()),
                ('duracao_em_segundos', models.IntegerField()),
            ],
            options={
                'unique_together': {('origem', 'destino')},
            },
        ),
        migrations.CreateModel(
            name='FornecedorMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\w{14}$')], verbose_name='CNPJ')),
                ('tipo_material', models.CharField(choices=[('CAR', 'Carvão Vegetal'), ('MIN', 'Minério')], max_length=3, verbose_name='Tipo de Material')),
                ('certificacao_ambiental', models.BooleanField(default=False, verbose_name='Certificação Ambiental')),
                ('licenca_operacao', models.CharField(blank=True, max_length=50, verbose_name='Licenca de Operação')),
                ('registro_ibama', models.CharField(blank=True, max_length=50, verbose_name='Registro IBAMA')),
                ('nota_qualidade', models.DecimalField(decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nota de Qualidade')),
                ('coordenadas_gps', models.CharField(blank=True, max_length=100, verbose_name='Coordenadas GPS')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores', to='map.cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores', to='map.estado')),
            ],
            options={
                'verbose_name': 'Fornecedor de Matéria Prima',
                'verbose_name_plural': 'Fornecedores de Matéria Prima',
                'ordering': ['razao_social'],
                'indexes': [models.Index(fields=['tipo_material'], name='map_fornece_tipo_ma_1a7c4d_idx'), models.Index(fields=['estado'], name='map_fornece_estado__493658_idx')],
            },
        ),
    ]
