# Generated by Django 5.1.3 on 2024-11-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedormateriaprima',
            name='coordenadas_gps',
        ),
        migrations.RemoveField(
            model_name='fornecedormateriaprima',
            name='licenca_operacao',
        ),
        migrations.RemoveField(
            model_name='fornecedormateriaprima',
            name='registro_ibama',
        ),
        migrations.AddField(
            model_name='fornecedormateriaprima',
            name='cadastro_tecnico_federal',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cadastro Técnico Federal'),
        ),
        migrations.AddField(
            model_name='fornecedormateriaprima',
            name='licenca',
            field=models.CharField(blank=True, max_length=50, verbose_name='Licença'),
        ),
        migrations.AddField(
            model_name='fornecedormateriaprima',
            name='registro_ief',
            field=models.CharField(blank=True, max_length=50, verbose_name='Registro IEF'),
        ),
    ]
