# Generated by Django 5.1.3 on 2024-11-09 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedormateriaprima',
            name='nome_fantasia',
        ),
    ]
