# Generated by Django 5.1.3 on 2024-11-09 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distancia',
            name='distancia',
        ),
        migrations.RemoveField(
            model_name='distancia',
            name='duracao',
        ),
    ]
