# Generated by Django 5.1.3 on 2024-11-10 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_remove_fornecedormateriaprima_coordenadas_gps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedormateriaprima',
            name='certificacao_ambiental',
        ),
    ]
