# Generated by Django 5.1.3 on 2024-11-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_remove_distancia_distancia_remove_distancia_duracao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Distancia',
            new_name='InfoRota',
        ),
    ]
