# Generated by Django 5.1.3 on 2024-11-12 00:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_remove_fornecedormateriaprima_certificacao_ambiental'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroTecnicoFederal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=50)),
                ('hyperlink', models.CharField(blank=True, max_length=255, null=True)),
                ('validade', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LicencaAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=50)),
                ('hyperlink', models.CharField(blank=True, max_length=255, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroIEF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=50)),
                ('hyperlink', models.CharField(blank=True, max_length=255, null=True)),
                ('validade', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='fornecedormateriaprima',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='fornecedormateriaprima',
            name='licenca',
        ),
        migrations.RemoveField(
            model_name='fornecedormateriaprima',
            name='nota_qualidade',
        ),
        migrations.AddField(
            model_name='fornecedormateriaprima',
            name='avaliacao',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Avaliação'),
        ),
        migrations.AddField(
            model_name='fornecedormateriaprima',
            name='cpf_cnpj',
            field=models.CharField(default='', max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^(\\w{14}|\\d{11})$')], verbose_name='CPF ou CNPJ'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='inforota',
            constraint=models.UniqueConstraint(fields=('origem', 'destino'), name='unique_origem_destino'),
        ),
        migrations.AddField(
            model_name='cadastrotecnicofederal',
            name='fornecedor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='map.fornecedormateriaprima'),
        ),
        migrations.AlterField(
            model_name='fornecedormateriaprima',
            name='cadastro_tecnico_federal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='map.cadastrotecnicofederal', verbose_name='Cadastro Técnico Federal'),
        ),
        migrations.AddField(
            model_name='licencaambiental',
            name='fornecedor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='map.fornecedormateriaprima'),
        ),
        migrations.AddField(
            model_name='fornecedormateriaprima',
            name='licenca_ambiental',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='map.licencaambiental', verbose_name='Licenca Ambiental'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroief',
            name='fornecedor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='map.fornecedormateriaprima'),
        ),
        migrations.AlterField(
            model_name='fornecedormateriaprima',
            name='registro_ief',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='map.registroief', verbose_name='Registro IEF'),
        ),
    ]
