# Generated by Django 5.1.3 on 2024-11-12 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_cadastrotecnicofederal_licencaambiental_registroief_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastrotecnicofederal',
            options={'verbose_name': 'Cadastro Técnico Federal', 'verbose_name_plural': 'Cadastro Técnico Federal'},
        ),
        migrations.AlterModelOptions(
            name='licencaambiental',
            options={'verbose_name': 'Licença Ambiental', 'verbose_name_plural': 'Licença Ambiental'},
        ),
        migrations.AlterModelOptions(
            name='registroief',
            options={'verbose_name': 'Registro IEF', 'verbose_name_plural': 'Registro IEF'},
        ),
        migrations.AlterField(
            model_name='fornecedormateriaprima',
            name='licenca_ambiental',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='map.licencaambiental', verbose_name='Licenca Ambiental'),
        ),
    ]
