# Generated by Django 5.1.3 on 2024-11-12 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_cadastrotecnicofederal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedormateriaprima',
            name='cadastro_tecnico_federal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.cadastrotecnicofederal', verbose_name='Cadastro Técnico Federal'),
        ),
        migrations.AlterField(
            model_name='fornecedormateriaprima',
            name='licenca_ambiental',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.licencaambiental', verbose_name='Licenca Ambiental'),
        ),
        migrations.AlterField(
            model_name='fornecedormateriaprima',
            name='registro_ief',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.registroief', verbose_name='Registro IEF'),
        ),
    ]
