# Generated by Django 5.1.3 on 2024-11-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_fornecedormateriaprima_cadastro_tecnico_federal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrotecnicofederal',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroief',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
