# Generated by Django 5.1.3 on 2024-11-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_delete_inforota_fornecedormateriaprima_distancia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedormateriaprima',
            old_name='distancia',
            new_name='distancia_em_metros',
        ),
    ]
