from plotly.graph_objects import Layout

custom_layout = Layout({
    'autotypenumbers': 'strict',
    'annotationdefaults': {'arrowcolor': '#2a3f5f', 'arrowhead': 0, 'arrowwidth': 1},
    'coloraxis': {'colorbar': {'outlinewidth': 0, 'ticks': ''}},
    'colorscale': {
        'diverging': [
            [0, '#8e0152'],
            [0.1, '#c51b7d'],
            [0.2, '#de77ae'],
            [0.3, '#f1b6da'],
            [0.4, '#fde0ef'],
            [0.5, '#f7f7f7'],
            [0.6, '#e6f5d0'],
            [0.7, '#b8e186'],
            [0.8, '#7fbc41'],
            [0.9, '#4d9221'],
            [1, '#276419'],
        ],
        'sequential': [
            [0.0, '#f4d4c7'],
            [1.0, '#d68367'],
        ],
        'sequentialminus': [
            [0.0, '#0d0887'],
            [0.1111111111111111, '#46039f'],
            [0.2222222222222222, '#7201a8'],
            [0.3333333333333333, '#9c179e'],
            [0.4444444444444444, '#bd3786'],
            [0.5555555555555556, '#d8576b'],
            [0.6666666666666666, '#ed7953'],
            [0.7777777777777778, '#fb9f3a'],
            [0.8888888888888888, '#fdca26'],
            [1.0, '#f0f921'],
        ],
    },
    'colorway': [
        '#d68367',
        '#EF553B',
        '#00cc96',
        '#ab63fa',
        '#636efa',
        '#19d3f3',
        '#FF6692',
        '#B6E880',
        '#FF97FF',
        '#FECB52',
    ],
    'geo': {
        'bgcolor': 'white',
        'lakecolor': 'white',
        'landcolor': '#E5ECF6',
        'showlakes': True,
        'showland': True,
        'subunitcolor': 'white',
    },
    'hoverlabel': {'align': 'auto'},
    'hovermode': 'closest',
    'paper_bgcolor': 'rgb(0,0,0,0)',
    'plot_bgcolor': '#151b25',
    'legend_bgcolor': '#151b25',
    'polar': {
        'angularaxis': {'gridcolor': 'white', 'linecolor': 'white', 'ticks': ''},
        'bgcolor': '#E5ECF6',
        'radialaxis': {'gridcolor': 'white', 'linecolor': 'white', 'ticks': ''},
    },
    'scene': {
        'xaxis': {
            'backgroundcolor': '#E5ECF6',
            'gridcolor': 'white',
            'gridwidth': 2,
            'linecolor': 'white',
            'showbackground': True,
            'ticks': '',
            'zerolinecolor': 'white',
        },
        'yaxis': {
            'backgroundcolor': '#E5ECF6',
            'gridcolor': 'white',
            'gridwidth': 2,
            'linecolor': 'white',
            'showbackground': True,
            'ticks': '',
            'zerolinecolor': 'white',
        },
        'zaxis': {
            'backgroundcolor': '#E5ECF6',
            'gridcolor': 'white',
            'gridwidth': 2,
            'linecolor': 'white',
            'showbackground': True,
            'ticks': '',
            'zerolinecolor': 'white',
        },
    },
    'shapedefaults': {'line': {'color': '#2a3f5f'}},
    'ternary': {
        'aaxis': {'gridcolor': 'white', 'linecolor': 'white', 'ticks': ''},
        'baxis': {'gridcolor': 'white', 'linecolor': 'white', 'ticks': ''},
        'bgcolor': '#E5ECF6',
        'caxis': {'gridcolor': 'white', 'linecolor': 'white', 'ticks': ''},
    },
    'xaxis': {
        'automargin': True,
        'ticks': '',
        'title': {'standoff': 5},
        'zerolinecolor': '#151b25',
        'zerolinewidth': 2,
    },
    'yaxis': {
        'automargin': True,
        'ticks': '',
        'title': {'standoff': 5},
        'zerolinecolor': '#151b25',
        'zerolinewidth': 2,
    },
    'margin': dict(l=200, r=200, t=50, b=50),
    'margin_autoexpand': True,
    # ! Modebar
    'modebar_remove': [
        'autoScale2d',
        'autoscale',
        'editInChartStudio',
        'editinchartstudio',
        'hoverCompareCartesian',
        'hovercompare',
        'lasso',
        'lasso2d',
        'orbitRotation',
        'orbitrotation',
        'pan',
        'pan2d',
        'pan3d',
        'reset',
        'resetCameraDefault3d',
        'resetCameraLastSave3d',
        'resetGeo',
        'resetSankeyGroup',
        'resetScale2d',
        'resetViewMap',
        'resetViewMapbox',
        'resetViews',
        'resetcameradefault',
        'resetcameralastsave',
        'resetsankeygroup',
        'resetscale',
        'resetview',
        'resetviews',
        'select',
        'select2d',
        'sendDataToCloud',
        'senddatatocloud',
        'tableRotation',
        'tablerotation',
        'toImage',
        'toggleHover',
        'toggleSpikelines',
        'togglehover',
        'togglespikelines',
        'toimage',
        'zoom',
        'zoom2d',
        'zoom3d',
        'zoomIn2d',
        'zoomInGeo',
        'zoomInMap',
        'zoomInMapbox',
        'zoomOut2d',
        'zoomOutGeo',
        'zoomOutMap',
        'zoomOutMapbox',
        'zoomin',
        'zoomout',
    ],
    # ! Font
    'font': dict(
        family='JetBrains Mono',
        size=12,
        color='white',
    ),
    # ! Title
    'title_font': dict(size=14, color='#f1f1f1'),
})
